### ISSUE TITLE
没有MODE_GCM啊

### ISSUE THREAD

**Issue by heiXing666** [unoemon/instagram-enc_passowrd-generator#1]
aes = AES.new(key, AES.MODE_GCM, mac_len=tag_length, nonce=iv)
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_GCM'

**Comment by unoemon** [comment]
@heiXing666 
Please try Python-3.7 and pycryptodome.

**Comment by heiXing666** [comment]
ok, thank you !


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"unoemon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 凌晨3:47
收件人:&nbsp;"unoemon/instagram-enc_passowrd-generator"<instagram-enc_passowrd-generator@noreply.github.com&gt;;
抄送： &nbsp;“ 1181426017” <1181426017@qq.com&gt;;“提及” <mention@noreply.github.com&gt;;
主题:&nbsp;Re: [unoemon/instagram-enc_passowrd-generator] 没有MODE_GCM啊 (#1)





 
@ heiXing666
  请尝试使用Python-3.7和pycryptodome。
  
- 
您收到此邮件是因为有人提到您。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
